### ISSUE TITLE
How do I use this tool?

### ISSUE THREAD

**Issue by Diego13303** [njshockey/bst-graph#3]
Excuse me for asking what´s probably a really dumb question, but I never use github and I can´t figure out where or how to use this tool. Is there a .exe file somewhere? Or is it something else? I´d really appreciate some help, and I apologize for the inconvenience

**Comment by njs-guy** [comment]
Sorry about this. This is a web app that I never got around to hosting on GitHub. I've really been meaning to but again, haven't gotten to it, yet.

**Comment by Diego13303** [comment]
Ah I see. Thanks for the quick reply! I hope you find time to host it soon

**Comment by njs-guy** [comment]
Alright, the site's up at https://njs-guy.github.io/bst-graph/

Really should have done this earlier lol.

**Comment by Diego13303** [comment]
Ooh just saw this! Thats awesome! Currently the little badges showing the types dont seem to be working right? They look ok in Dark Mode, but they´re impossible to read in Light Mode
![image](https://github.com/njs-guy/bst-graph/assets/91715852/8679bf30-bf3c-4205-bee9-db82910c1619)
![image](https://github.com/njs-guy/bst-graph/assets/91715852/c16fbf8b-1a87-436a-899d-ccec4d6f2fcb)

**Comment by njs-guy** [comment]
That's weird. What browser are you using? Works for me in Chrome and Firefox.

**Comment by Diego13303** [comment]
Odd.. I´m using Google Chrome as well :/
